package com.bankingsystem.entity;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    REGISTER,
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    ACCOUNT_FREEZE,
    ACCOUNT_UNFREEZE,
    LOAN_APPLIED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    CARD_REQUESTED,
    CARD_ACTIVATED,
    CARD_BLOCKED,
    CARD_UNBLOCKED,
    CARD_LIMIT_UPDATED,
    BENEFICIARY_ADDED,
    BENEFICIARY_DELETED,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,
    SETTINGS_UPDATED,
    SECURITY_EVENT
}
